### ISSUE TITLE
OK,Thank you very much!

### ISSUE THREAD

**Issue by danganyuan** [puckikk1202/difffacesketch2023#11]
OK,Thank you very much!

_Originally posted by @OrangeZz0331 in https://github.com/puckikk1202/difffacesketch2023/issues/4#issuecomment-1844151351_

**Comment by danganyuan** [comment]
Hello! Have you completed the replication of DiffFaceSketch? How were the results? If it's convenient, could I ask you for some advice on it?

**Comment by danganyuan** [comment]
Hello, I would like to ask you for some knowledge about this project. If you are available, could you please contact me at my email address 18860329267@163.com? Alternatively, could you provide me with your contact information? Thank you very much.

**Comment by OrangeZz0331** [comment]
Sorry,I haven't completed it and I give it up now.
