### ISSUE TITLE
About "train_ae.py" file

### ISSUE THREAD

**Issue by 9ww1** [puckikk1202/difffacesketch2023#13]
Hello, I wish to train an AE module tailored to my dataset, but I encountered two classes, combine_AE and combine_AE_dilate. In the trainae.py file, the initialization seems to be for the combine_AE_dilate. Why is this? May I initialize the combine_AE class for training purposes?

**Comment by puckikk1202** [comment]
Hi, it depends on your task. combine_AE would be fit for a high-consistency reconstruction task. While the dilation one would mainly focus on the sketch input.

**Comment by 9ww1** [comment]
Thank you very much for your response. I am engaged in work similar to facial image generation, and I believe we should train combine_AE.

**Comment by 9ww1** [comment]
> Hi, it depends on your task. combine_AE would be fit for a high-consistency reconstruction task. While the dilation one would mainly focus on the sketch input.

Thank you very much for your response. I am engaged in work similar to facial image generation, and I believe we should train combine_AE.

**Comment by 9ww1** [comment]
> Hi, it depends on your task. combine_AE would be fit for a high-consistency reconstruction task. While the dilation one would mainly focus on the sketch input.

Thank you very much for your response. I am engaged in work similar to facial image generation, and I believe we should train combine_AE.
