### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by OrangeZz0331** [puckikk1202/difffacesketch2023#2]
I have encountered an error,can you tell me how to solve it.
![ERROR](https://github.com/puckikk1202/difffacesketch2023/assets/148956633/24c9dbe8-a700-40f3-9b66-e287cb00cfee)

**Comment by puckikk1202** [comment]
Maybe you should first get into the root file by
`cd your/file/path`

**Comment by OrangeZz0331** [comment]
OK！Thanks！

**Comment by OrangeZz0331** [comment]
Excuse me，can you help me solve this problem?What should I do?
![Uploading ERROR2.png…]()

**Comment by OrangeZz0331** [comment]
Excuse me，can you help me solve this problem?What should I do?
<img width="484" alt="ERROR2" src="https://github.com/puckikk1202/difffacesketch2023/assets/148956633/4a3eb602-82f7-4c3f-81c5-8b3309fcf375">

**Comment by OrangeZz0331** [comment]
Excuse me，can you help me solve this problem?What should I do?
<img width="716" alt="ERROR2" src="https://github.com/puckikk1202/difffacesketch2023/assets/148956633/cfcea72f-69df-4136-b18d-41edc285f62a">

**Comment by puckikk1202** [comment]
It seems there were some environment value depended on the local environment.  In requirements.txt, try to modify line 57
`-e d:\improved-diffusion-main` into `-e https://github.com/openai/improved-diffusion.git`
Hope this will work.

**Comment by OrangeZz0331** [comment]
**Thank you very much!**
But the "requirements.txt" may be have other environment values depended on the local environment.Can you help me modify the text?
This is another error:
![ERROR3](https://github.com/puckikk1202/difffacesketch2023/assets/148956633/1c8fbc12-b7bc-4b32-bec7-b6c7110750ef)

**Comment by puckikk1202** [comment]
I have updated the requirements.txt file. Please try it out. 
If you encounter any issues due to different environment settings, you may skip the problematic entries and proceed with running the code. Should those entries prove necessary, please install them manually. Thank you!

**Comment by OrangeZz0331** [comment]
Thank you very much!
