### ISSUE TITLE
pretrained_mode

### ISSUE THREAD

**Issue by ludandandan** [puckikk1202/difffacesketch2023#5]

**Comment by ludandandan** [comment]
Is  model = load_model_from_config(config, "ldm_vae/models/first_stage_models/vq-f4/model.ckpt") refer to the "ae.pt" in pretrained_models ?

**Comment by ludandandan** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'ldm_vae/models/first_stage_models/vq-f4/model.ckpt'

**Comment by puckikk1202** [comment]
hi, you should download the .ckpt [here](https://ommer-lab.com/files/latent-diffusion/vq-f4.zip), related to LDM [repo](https://github.com/CompVis/latent-diffusion)

**Comment by ludandandan** [comment]
好，Thank you very much~~~~

**Comment by puckikk1202** [comment]
You are welcome. 
By the way, the ae.pt is related to the multi-ae. Please put it into your customized directory.

**Comment by ludandandan** [comment]
ok，Thank you so much!
