### ISSUE TITLE
dataset 

### ISSUE THREAD

**Issue by ludandandan** [puckikk1202/difffacesketch2023#6]
Hi～Thank you very much for your previous reply! And I found there is "from sketch_ae.datasets.celeba_sketch import CelebaSketch" in train_ae.py, can you share the "celeba_sketch"? I would like to refer to this to process my own data.

**Comment by puckikk1202** [comment]
Sorry, for the inconvenient, [ddpm/celeba_dataset.py](https://github.com/puckikk1202/difffacesketch2023/blob/4b30efd9bebc3b4245d3aaaceeeff2b456544ad5/ddpm/celeba_dataset.py#L92C36-L92C36) script is here.

**Comment by ludandandan** [comment]
Thank you~, There are 5 CelebaSketch Dataset,which is need in train_ae.py?
![image](https://github.com/puckikk1202/difffacesketch2023/assets/32790817/9e81aaab-36c6-4f6d-95ae-62606bb9b747)

**Comment by puckikk1202** [comment]
`class CelebaSketch(Dataset):
    def __init__(self, data_dir, transform=None):
        self.data_dir = data_dir
        self.transform = transform

    def __len__(self):
        return len(os.listdir(self.data_dir))

    def __getitem__(self, idx):
        if torch.is_tensor(idx):
            idx = idx.tolist()

        file = os.listdir(self.data_dir)[idx]
        img = Image.open(os.path.join(self.data_dir, file)).convert('L')
        if self.transform:
            img = self.transform(img)

        return img`
        Sorry wrong file, maybe directly use this one.

**Comment by puckikk1202** [comment]
`class CelebaSketch(Dataset):
    def __init__(self, data_dir, transform=None):
        self.data_dir = data_dir
        self.transform = transform

    def __len__(self):
        return len(os.listdir(self.data_dir))

    def __getitem__(self, idx):
        if torch.is_tensor(idx):
            idx = idx.tolist()

        file = os.listdir(self.data_dir)[idx]
        img = Image.open(os.path.join(self.data_dir, file)).convert('L')
        if self.transform:
            img = self.transform(img)

        return img`

**Comment by puckikk1202** [comment]
`
class CelebaSketch(Dataset):
    def __init__(self, data_dir, transform=None):
        self.data_dir = data_dir
        self.transform = transform
    def __len__(self):
        return len(os.listdir(self.data_dir))
    def __getitem__(self, idx):
        if torch.is_tensor(idx):
            idx = idx.tolist()
        file = os.listdir(self.data_dir)[idx]
        img = Image.open(os.path.join(self.data_dir, file)).convert('L')
        if self.transform:
            img = self.transform(img)
        return img
`

**Comment by puckikk1202** [comment]
class CelebaSketch(Dataset):
    def __init__(self, data_dir, transform=None):
        self.data_dir = data_dir
        self.transform = transform

    def __len__(self):
        return len(os.listdir(self.data_dir))

    def __getitem__(self, idx):
        if torch.is_tensor(idx):
            idx = idx.tolist()

        file = os.listdir(self.data_dir)[idx]
        img = Image.open(os.path.join(self.data_dir, file)).convert('L')
        if self.transform:
            img = self.transform(img)

        return img
        
Maybe this one.

**Comment by puckikk1202** [comment]
Sorry wrong file, I have pushed. Please check it.

**Comment by ludandandan** [comment]
Thank you so much!
