### ISSUE TITLE
loss in train_ae.py

### ISSUE THREAD

**Issue by ludandandan** [puckikk1202/difffacesketch2023#8]
Hello，I am confused in the loss in train_ae.py. Why only use one sample to compute MSE loss in a batch，and why kld loss is equal to the second sample feature?
![image](https://github.com/puckikk1202/difffacesketch2023/assets/32790817/ffa4a993-b029-4230-b7e0-11aa38cb37cb)

If I have any misunderstandings, please correct them. And  the kld loss is shape [1,64,64] cause RuntimeError: grad can be implicitly created only for scalar outputs.

**Comment by puckikk1202** [comment]
Apologies for the alignment of the code. The KLD loss calculation, which you might need for training a Variational Autoencoder (VAE), is currently commented out [here](https://github.com/puckikk1202/difffacesketch2023/blob/d85735dc3944b605b5f94795b5008a152fe47e7a/sketch_ae/models/Combine_AE_dilate.py#L158). If you intend to train an Autoencoder (AE) instead, you will need to adjust the output configuration accordingly.

**Comment by ludandandan** [comment]
aoao，thank you to reply
